### ISSUE TITLE
publish on conda to use GPU packages like cupy and cuML

### ISSUE THREAD

**Issue by gavinmischler** [naplab/naplib-python#109]
publish on conda-forge

**Comment by beckernick** [comment]
HI! I came across this issue based on the cuML reference.

Just wanted to mention that [cuML](https://rapids.ai/#quick-start) and [CuPy](https://docs.cupy.dev/en/stable/install.html#installing-cupy) packages can be installed via pip, too! Happy to try to answer any questions you might have.

**Comment by gavinmischler** [comment]
Oh ok cool! So if we simply add CuPy to our requirements.txt, will it work when you pip install our package on a machine with a GPU?

**Comment by beckernick** [comment]
Generally speaking, yes it should. You may not be able to install CuPy without a GPU present, though.

cuML will also require using the `extra-index-url` option.

**Comment by gavinmischler** [comment]
Got it, thanks so much for finding this issue and for the help!
